import { describe, expect, it } from "vitest";
import { readFileSync, readdirSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { filterLines, processGame } from "../src/index.js";

/**
 * Regression suite against the 345 real historical gamelogs in fixtures/gamelogs.
 *
 * fixtures/ground_truth/*.json was generated by actually running v1's catan2.py
 * process_game() against each fixture (see the one-off script used to produce it,
 * not checked in — it's a byte-for-byte dump of v1's real output). Two groups:
 *
 * 1. Fixtures where v1 succeeded: the TS port must match v1's output exactly.
 *    This is what validates the port is a faithful translation, not a rewrite.
 * 2. Fixtures where v1 *crashed* (91 of 345 — see CLAUDE.md and the
 *    LONGEST_PASSED_RE/LARGEST_PASSED_RE comments in processGame.ts for why):
 *    there's no v1 ground truth to compare against, so these just assert the
 *    TS port parses successfully and lands on a sane winner/points, which v1
 *    could not do at all.
 */

const HERE = path.dirname(fileURLToPath(import.meta.url));
const FIXTURES_ROOT = path.resolve(HERE, "../../../fixtures");
const GAMELOGS_DIR = path.join(FIXTURES_ROOT, "gamelogs");
const GROUND_TRUTH_DIR = path.join(FIXTURES_ROOT, "ground_truth");

const hasFixtures = existsSync(GAMELOGS_DIR) && existsSync(GROUND_TRUTH_DIR);

function loadFixtureLines(name: string): string[] {
  const raw = readFileSync(path.join(GAMELOGS_DIR, name), "utf-8").split("\n");
  // mirror read_and_filter_lines(): drop the trailing empty element from a final newline
  const trimmed = raw[raw.length - 1] === "" ? raw.slice(0, -1) : raw;
  return filterLines(trimmed);
}

describe.skipIf(!hasFixtures)("parser vs v1 ground truth", () => {
  const allGames = readdirSync(GAMELOGS_DIR)
    .filter((f) => f.endsWith(".txt"))
    .sort();
  const groundTruthGames = new Set(readdirSync(GROUND_TRUTH_DIR).map((f) => f.replace(".json", ".txt")));

  const parityGames = allGames.filter((f) => groundTruthGames.has(f));
  const crashGames = allGames.filter((f) => !groundTruthGames.has(f));

  it("has the expected fixture split (sanity check on the fixtures themselves)", () => {
    expect(allGames.length).toBe(345);
    // if this drifts, someone changed catan2.py, the fixtures, or fixed the bug
    // upstream — re-run the ground-truth dump and update this expectation deliberately
    expect(parityGames.length).toBe(254);
    expect(crashGames.length).toBe(91);
  });

  describe("exact parity with v1 (games v1 parsed successfully)", () => {
    for (const file of parityGames) {
      it(`matches v1 output for ${file}`, () => {
        const lines = loadFixtureLines(file);
        const result = processGame(lines);
        const groundTruth = JSON.parse(readFileSync(path.join(GROUND_TRUTH_DIR, file.replace(".txt", ".json")), "utf-8"));

        expect(result.winner).toBe(groundTruth.winner);
        expect(result.players).toEqual(groundTruth.players);
        expect(result.playerOrder).toEqual(groundTruth.playerOrder);
        expect(result.playerPoints).toEqual(groundTruth.playerPoints);
        expect(result.dice).toEqual(groundTruth.dice);
        expect(result.turn).toBe(groundTruth.turn);
        expect(result.resourcesPerPlayer).toEqual(groundTruth.resourcesPerPlayer);
        expect(result.stealMap).toEqual(groundTruth.stealMap);
        expect(result.trades).toEqual(groundTruth.trades);
        expect(result.playerDiceRolls).toEqual(groundTruth.playerDiceRolls);
        // no warnings expected when v1 itself didn't choke on this file
        expect(result.warnings).toEqual([]);
      });
    }
  });

  describe("survives v1's known crashers (longest-road/largest-army wording drift)", () => {
    for (const file of crashGames) {
      it(`parses ${file} without throwing, on a real player, with 4 players seated`, () => {
        const lines = loadFixtureLines(file);
        const result = processGame(lines);

        // The bar here is "v1 crashed and produced nothing; v2 doesn't crash and
        // produces a plausible result" — not perfect point math. Some of these
        // games may still under-count points from causes unrelated to the
        // longest-road/largest-army fix (e.g. hidden VP dev cards not always
        // announced with parseable text in the log, a pre-existing v1 limitation).
        expect(Object.keys(result.players).length).toBe(4);
        expect(result.winner).not.toBe("");
        expect(result.winner in result.players).toBe(true);
        expect(result.winner).not.toBe("longest");
        expect(result.winner).not.toBe("largest");
      });
    }
  });
});
